/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authAuthRouteRouteImport } from './routes/(auth)/_auth/route'
import { Route as workspaceProtectedRouteRouteImport } from './routes/(workspace)/_protected/route'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth/login'
import { Route as workspaceProtectedNotesRouteImport } from './routes/(workspace)/_protected/notes'
import { Route as workspaceProtectedPomodoroRouteImport } from './routes/(workspace)/_protected/pomodoro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRouteRoute = authAuthRouteRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const workspaceProtectedRouteRoute = workspaceProtectedRouteRouteImport.update({
  id: '/(workspace)/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const workspaceProtectedNotesRoute = workspaceProtectedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => workspaceProtectedRouteRoute,
} as any)
const workspaceProtectedPomodoroRoute =
  workspaceProtectedPomodoroRouteImport.update({
    id: '/pomodoro',
    path: '/pomodoro',
    getParentRoute: () => workspaceProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/notes': typeof workspaceProtectedNotesRoute
  '/pomodoro': typeof workspaceProtectedPomodoroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/notes': typeof workspaceProtectedNotesRoute
  '/pomodoro': typeof workspaceProtectedPomodoroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth': typeof authAuthRouteRouteWithChildren
  '/(workspace)/_protected': typeof workspaceProtectedRouteRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(workspace)/_protected/notes': typeof workspaceProtectedNotesRoute
  '/(workspace)/_protected/pomodoro': typeof workspaceProtectedPomodoroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/notes' | '/pomodoro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/notes' | '/pomodoro'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth'
    | '/(workspace)/_protected'
    | '/(auth)/_auth/login'
    | '/(workspace)/_protected/notes'
    | '/(workspace)/_protected/pomodoro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthRouteRoute: typeof authAuthRouteRouteWithChildren
  workspaceProtectedRouteRoute: typeof workspaceProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspace)/_protected': {
      id: '/(workspace)/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof workspaceProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(workspace)/_protected/notes': {
      id: '/(workspace)/_protected/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof workspaceProtectedNotesRouteImport
      parentRoute: typeof workspaceProtectedRouteRoute
    }
    '/(workspace)/_protected/pomodoro': {
      id: '/(workspace)/_protected/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof workspaceProtectedPomodoroRouteImport
      parentRoute: typeof workspaceProtectedRouteRoute
    }
  }
}

interface authAuthRouteRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteRouteChildren: authAuthRouteRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteRouteWithChildren = authAuthRouteRoute._addFileChildren(
  authAuthRouteRouteChildren,
)

interface workspaceProtectedRouteRouteChildren {
  workspaceProtectedNotesRoute: typeof workspaceProtectedNotesRoute
  workspaceProtectedPomodoroRoute: typeof workspaceProtectedPomodoroRoute
}

const workspaceProtectedRouteRouteChildren: workspaceProtectedRouteRouteChildren =
  {
    workspaceProtectedNotesRoute: workspaceProtectedNotesRoute,
    workspaceProtectedPomodoroRoute: workspaceProtectedPomodoroRoute,
  }

const workspaceProtectedRouteRouteWithChildren =
  workspaceProtectedRouteRoute._addFileChildren(
    workspaceProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthRouteRoute: authAuthRouteRouteWithChildren,
  workspaceProtectedRouteRoute: workspaceProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
