/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authAuthRouteRouteImport } from './routes/(auth)/_auth/route'
import { Route as workspaceProtectedRouteRouteImport } from './routes/(workspace)/_protected/route'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth/login'
import { Route as authAuthRegisterRouteImport } from './routes/(auth)/_auth/register'
import { Route as workspaceProtectedSettingsRouteImport } from './routes/(workspace)/_protected/settings'
import { Route as workspaceProtectedNotesIndexRouteImport } from './routes/(workspace)/_protected/notes/index'
import { Route as workspaceProtectedNotesNoteIdRouteImport } from './routes/(workspace)/_protected/notes/$noteId'
import { Route as workspaceProtectedNotesSharedRouteImport } from './routes/(workspace)/_protected/notes/shared'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRouteRoute = authAuthRouteRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const workspaceProtectedRouteRoute = workspaceProtectedRouteRouteImport.update({
  id: '/(workspace)/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const workspaceProtectedSettingsRoute =
  workspaceProtectedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => workspaceProtectedRouteRoute,
  } as any)
const workspaceProtectedNotesIndexRoute =
  workspaceProtectedNotesIndexRouteImport.update({
    id: '/notes/',
    path: '/notes/',
    getParentRoute: () => workspaceProtectedRouteRoute,
  } as any)
const workspaceProtectedNotesNoteIdRoute =
  workspaceProtectedNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => workspaceProtectedRouteRoute,
  } as any)
const workspaceProtectedNotesSharedRoute =
  workspaceProtectedNotesSharedRouteImport.update({
    id: '/notes/shared',
    path: '/notes/shared',
    getParentRoute: () => workspaceProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/register': typeof authAuthRegisterRoute
  '/settings': typeof workspaceProtectedSettingsRoute
  '/notes/$noteId': typeof workspaceProtectedNotesNoteIdRoute
  '/notes/shared': typeof workspaceProtectedNotesSharedRoute
  '/notes/': typeof workspaceProtectedNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/register': typeof authAuthRegisterRoute
  '/settings': typeof workspaceProtectedSettingsRoute
  '/notes/$noteId': typeof workspaceProtectedNotesNoteIdRoute
  '/notes/shared': typeof workspaceProtectedNotesSharedRoute
  '/notes': typeof workspaceProtectedNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth': typeof authAuthRouteRouteWithChildren
  '/(workspace)/_protected': typeof workspaceProtectedRouteRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(auth)/_auth/register': typeof authAuthRegisterRoute
  '/(workspace)/_protected/settings': typeof workspaceProtectedSettingsRoute
  '/(workspace)/_protected/notes/$noteId': typeof workspaceProtectedNotesNoteIdRoute
  '/(workspace)/_protected/notes/shared': typeof workspaceProtectedNotesSharedRoute
  '/(workspace)/_protected/notes/': typeof workspaceProtectedNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/notes/$noteId'
    | '/notes/shared'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/notes/$noteId'
    | '/notes/shared'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth'
    | '/(workspace)/_protected'
    | '/(auth)/_auth/login'
    | '/(auth)/_auth/register'
    | '/(workspace)/_protected/settings'
    | '/(workspace)/_protected/notes/$noteId'
    | '/(workspace)/_protected/notes/shared'
    | '/(workspace)/_protected/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthRouteRoute: typeof authAuthRouteRouteWithChildren
  workspaceProtectedRouteRoute: typeof workspaceProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspace)/_protected': {
      id: '/(workspace)/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof workspaceProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(auth)/_auth/register': {
      id: '/(auth)/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(workspace)/_protected/settings': {
      id: '/(workspace)/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof workspaceProtectedSettingsRouteImport
      parentRoute: typeof workspaceProtectedRouteRoute
    }
    '/(workspace)/_protected/notes/': {
      id: '/(workspace)/_protected/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof workspaceProtectedNotesIndexRouteImport
      parentRoute: typeof workspaceProtectedRouteRoute
    }
    '/(workspace)/_protected/notes/$noteId': {
      id: '/(workspace)/_protected/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof workspaceProtectedNotesNoteIdRouteImport
      parentRoute: typeof workspaceProtectedRouteRoute
    }
    '/(workspace)/_protected/notes/shared': {
      id: '/(workspace)/_protected/notes/shared'
      path: '/notes/shared'
      fullPath: '/notes/shared'
      preLoaderRoute: typeof workspaceProtectedNotesSharedRouteImport
      parentRoute: typeof workspaceProtectedRouteRoute
    }
  }
}

interface authAuthRouteRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
}

const authAuthRouteRouteChildren: authAuthRouteRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
}

const authAuthRouteRouteWithChildren = authAuthRouteRoute._addFileChildren(
  authAuthRouteRouteChildren,
)

interface workspaceProtectedRouteRouteChildren {
  workspaceProtectedSettingsRoute: typeof workspaceProtectedSettingsRoute
  workspaceProtectedNotesNoteIdRoute: typeof workspaceProtectedNotesNoteIdRoute
  workspaceProtectedNotesSharedRoute: typeof workspaceProtectedNotesSharedRoute
  workspaceProtectedNotesIndexRoute: typeof workspaceProtectedNotesIndexRoute
}

const workspaceProtectedRouteRouteChildren: workspaceProtectedRouteRouteChildren =
  {
    workspaceProtectedSettingsRoute: workspaceProtectedSettingsRoute,
    workspaceProtectedNotesNoteIdRoute: workspaceProtectedNotesNoteIdRoute,
    workspaceProtectedNotesSharedRoute: workspaceProtectedNotesSharedRoute,
    workspaceProtectedNotesIndexRoute: workspaceProtectedNotesIndexRoute,
  }

const workspaceProtectedRouteRouteWithChildren =
  workspaceProtectedRouteRoute._addFileChildren(
    workspaceProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthRouteRoute: authAuthRouteRouteWithChildren,
  workspaceProtectedRouteRoute: workspaceProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
